### ISSUE TITLE
ImportError: cannot import name 'MediaWiki' from 'mediawiki'

### ISSUE THREAD

**Issue by FlashlightET** [barrust/mediawiki#129]
used to work fine but now it does this ever since i updated python to 3.8.16

this happens simply when i run from mediawiki import MediaWiki

i am using pymediawiki-0.7.2

**Comment by barrust** [comment]
What is the exact error? I am unable to reproduce it but with more information perhaps I can help.

**Comment by barrust** [comment]
A new version was pushed recently, perhaps updating it will resolve the issue. 

If updating doesn't please reopen this issue.
